logging:
  level:
    '[com.laundry.BE_Laundry]': TRACE
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    
spring:
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
      
  datasource:
    hikari:
      connection-timeout: 300000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
    url: jdbc:postgresql://host.docker.internal:5432/db-laundry
    driver-class-name: org.postgresql.Driver
    username: subrutin
    password: subrutin
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
    properties:
     hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 100
        order_inserts: true
    show-sql: true

server:
  servlet:
     context-path: 

     
  thymeleaf:  
    prefix: classpath:/templates/
    suffix: .html
---
#spring:
#  config:
#    activate:
#      on-profile: test
#server:
#  port: 5052


---
spring:
  config:
    activate:
      on-profile: development
server:
  port: 9090


---
#spring:
#  config:
#    activate:
#      on-profile: production
#server:
#  port : 102