services:
  postgres_db:
    image: postgres:17-alpine3.21
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: subrutin #your required name 
      POSTGRES_PASSWORD: subrutin # your required password 
      POSTGRES_DB: db-laundry
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
