version: '3.3'

services:
  db:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: subrutin #your required name 
      POSTGRES_PASSWORD: subrutin # your required password 
      POSTGRES_DB: db-laundry